force-app/main/default/objects/Areas_of_Interest_Level_1_Value__mdt/Areas_of_Interest_Level_1_Value__mdt.object-meta.xml
<CustomObject>
    <label>Areas of Interest Level 1 Value</label>
    <pluralLabel>Areas of Interest Level 1 Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Areas_of_Interest_Level_2_Value__mdt/Areas_of_Interest_Level_2_Value__mdt.object-meta.xml
<CustomObject>
    <label>Areas of Interest Level 2 Value</label>
    <pluralLabel>Areas of Interest Level 2 Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/Areas_of_Interest_Level_2_Value__mdt/fields/Level_1__c.field-meta.xml
<CustomField>
    <fullName>Level_1__c</fullName>
    <label>Level 1</label>
    <referenceTo>Areas_of_Interest_Level_1_Value__mdt</referenceTo>
    <relationshipLabel>Areas of Interest Level 2 Values</relationshipLabel>
    <relationshipName>Areas_of_Interest_Level_2_Values</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/AreasOfInterestController.cls
public without sharing class AreasOfInterestController {
  @AuraEnabled(Cacheable=true)
  public static List<Areas_of_Interest_Level_1_Value__mdt> getLevelOneAndRelatedLevelTwoValues() {
    try {
      return [
        SELECT
          Id,
          MasterLabel,
          DeveloperName,
          (
            SELECT Id, MasterLabel, DeveloperName
            FROM Areas_of_Interest_Level_2_Values__r
          )
        FROM Areas_of_Interest_Level_1_Value__mdt
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}